version: "3.7"

services:
  server:
    build: 
      context: ./back-end
      dockerfile: Dockerfile
    container_name: shopify-server
    volumes:
      - ./back-end/:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - "5000:5000"
    depends_on:
      - mongo
    env_file: ./back-end/.env
    networks:
      - app-network
  mongo:
    image: mongo
    volumes:
      - data-volume:/data/db
    environment:
      - MONGO_INITDB_DATABASE=shopify
    ports:
      - "27017:27017"
    networks:
      - app-network
  client:
    build: 
      context: ./front-end
      dockerfile: Dockerfile
    container_name: shopify-client
    volumes:
      - ./front-end/:/usr/app
      - /usr/app/node_modules
    depends_on:
      - server
    environment:
      - PORT=80
      - DANGEROUSLY_DISABLE_HOST_CHECK=true
    ports:
      - "80:80"
    networks:
      - app-network
networks:
  app-network:
    driver: bridge
volumes:
  data-volume:
  node_modules:
  web-root:
    driver: local
